# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'sobre mí',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'gmail', link:   'hafsakatkout@gmail.com'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Nuevo'
  previous_page: 'anterior'

sharing_button_prompt: 'aqui puedes compartir!'

related_posts: 'Qué opinas de más publicaciones :'

post_date_prefix: 'publicado en'
